# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 001353e3d51b71afd10409e38faa55251db5043a5884a4a203802b9a043b08da236036ef80fb49748d5758da78121d7aebf8dd93fc877714f6f87257a4d54b29

test:
  secret_key_base: 0b9d2415b3bed910adb930ca88c6ea7363eee840bfe905961cbcf92d1b8eda4acef72f2f5bb9afd080b13686f23f61714e9923ba97c60e4e572a8825c05b1017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
